### ISSUE TITLE
Some Errors

### ISSUE THREAD

**Issue by LVPYassine** [Sreyas-Sreelal/SS-Teleport-Master-Include#1]
Hi !

when i updated my script using u inc file :) i get some errors (8)

sames errors

error 035: argument type mismatch (argument 2)

line : 

> `if(!IsPlayerInAnyVehicle(playerid)) return TeleportPlayer(playerid, "Los Santos Stunts", 1040.8041, -1032.2076, 32.0148, 0, 0, true, "~g~Welcome To LS Stunts", true);`

**Comment by Sreyas-Sreelal** [comment]
`TeleportPlayer(playerid, Float:X, Float:Y, Float:Z, Float:A, interior = -1, virtualworld = -1, bool:load = false, gametext[] = "", location[] = "")`
the correct parameters ^^^
your code should be 
`TeleportPlayer(playerid, 1040.8041, -1032.2076, 32.0148, 0.0, 0, 0,true,"~g~Welcome To LS Stunts","Los Santos Stunts");`
Also no need to check whether the player is in vehicle the include does that.

**Comment by LVPYassine** [comment]
This Include  can check Player state and teleport Vehicle too ?

**Comment by LVPYassine** [comment]
and i think u need to edit Readme.md

**Comment by Sreyas-Sreelal** [comment]
Yeah it can.
and yeah thank you for reporting that i used old params in readme but did not update that in read me thanks.
